# Generated by Django 3.2.8 on 2021-10-28 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'authors',
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Genre Title')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'genres',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Book Title')),
                ('synopsis', models.TextField(verbose_name='Synopsis')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price in cents')),
                ('genres', models.ManyToManyField(db_index=True, to='books.Genre', verbose_name='Genre')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author', verbose_name='Writer')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
                'ordering': ('name', 'genres__name', 'release_date', 'price'),
            },
        ),
    ]
